name = "OSMMakie"
uuid = "76b6901f-8821-46bb-9129-841bc9cfe677"
authors = ["Frederik Banning <frederik.banning@ruhr-uni-bochum.de>"]
version = "0.0.4"

[deps]
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LightOSM = "d1922b25-af4e-4ba3-84af-fe9bea896051"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
julia = "1.6, 1.7"
GraphMakie = "0.3"
Graphs = "1.5"
LightOSM = "0.1"
Makie = "0.15, 0.16"
